### ISSUE TITLE
Support LSDYNA example

### ISSUE THREAD

**Issue by samigithub2022** [ansys/pymechanical-examples#52]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

In Standalone Mechanical

LSDYNA example didn't work based on 232 docker image. 231 had LSDYNA support.

Support this example for 241.

### 📝 Steps to reproduce

PR #34 shows this issue.

### 💻 Which operating system are you using?

Linux

### 📀 Which ANSYS version are you using?

232 - Standalone Mechanical

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-api-mechanical==0.1.0
ansys-api-platform-instancemanagement==1.0.0b3
ansys-mechanical-core==0.9.1
ansys-platform-instancemanagement==1.1.1
ansys-pythonnet==3.1.0rc1
ansys-tools-path==0.2.6
appdirs==1.4.4
cffi==1.15.1
clr-loader==0.2.5
googleapis-common-protos==1.59.1
grpcio==1.56.0
importlib-metadata==6.7.0
protobuf==3.20.3
protoc-gen-swagger==0.1.0
pycparser==2.21
tqdm==4.65.0
zipp==3.15.0
```

**Comment by koubaa** [comment]
I suggest documenting this, and adding a unit test once fixed

**Comment by dipinknair** [comment]
#34
